# ![Imgur](https://i.imgur.com/5pXzCIu.png)

# **DATA SCIENCE VA SUN'IY INTELLEKT PRAKTIKUM**

## NumPy kutubxonasida massiv yaratish

## 2.1.1 Series va Index

# ![Imgur](https://i.imgur.com/Fgd43iK.png?1)

# **Ushbu Javoblar toplami kimlargadir yordami tegsa Xursand bo'laman.**

### Do'stlaringizga ham ulashing. 
### Balki ularga ham yordami tegib qolar

Faqatgina `YOUR CODE HERE` yoki "YOUR ANSWER HERE" deyilgan joyga dasturingizni yoki javobingizni yozing

---

---
# Ma'lumotlar tahlili

## 2.1.1. N-O'lchovli massivlarga ishlov berish

## Vazifa-2

In [ ]:
# Numpy kutubxonasini chaqirib olish
import numpy as np

### Masala(1): 2-o'lchamli massiv yaratish (1 point)

**Masala sharti :** Elementlari 0 dan 9 gacha (9 ning o'zi massiv elementiga kirmaydi), qadami esa 1 ga teng bo'lgan (3, 3) o'lchamli massiv yarating. 

**Yordam :**  `arange`dan foydalanish ishni osonlashtiradi 


In [ ]:
def nd_array():
    """Elementlari 0 dan 9 gacha (9 ning o'zi massiv elementiga kirmaydi), qadami esa 1 ga teng bo'lgan (3, 3) o'lchamli massiv """
    # YOUR CODE HERE
    return np.arange(9).reshape(3,3)
    raise NotImplementedError()

Sizning funksiyangiz massiv elementlari soni, `shape` massiv shakli, hamda elementlari 0~10 oralig'idagi numpy array ekanligi orqali tekshiriladi. Bundan tashqari bir qancha maxfiy testlardan o'tkaziladi (maslahatimiz aldashga urinmang). 

In [ ]:
"""Funksiyani tekshirish"""
arr = nd_array() # massiv
assert arr.size == 9  # elementlar soni
assert type(arr) == np.ndarray # #numpy array 

###  Masala(2): Indeks yordamida 2-o'lchamli massivlardan elementlarni  kesib olish (3 points)

**Masala :** Yuqorida yaratilgan massivning elementlari 6 va 7 ga teng bo'lgan qismini kesib olish funksiyasini tuzing.

**Yordam :** 6 va 7 turgan indekslarni aniqlab olib, shu indekslar yordamida kesib oling. **Natija:** array([6, 7]) ko'rinishida bo'lishi kerak. 

In [ ]:
def sliced_array_2d():
    """Yuqorida yaratilgan massivning elementlari 6 va 7 ga teng bo'lgan qismini kesib olish funksiyasi """
    # YOUR CODE HERE
    return arr[2,:2]
    raise NotImplementedError()

Sizning funksiyangiz massiv elementlari soni, `shape` massiv shakli, hamda elementlari numpy array ekanligi orqali tekshiriladi. Bundan tashqari bir qancha maxfiy testlardan o'tkaziladi (maslahatimiz aldashga urinmang). 

In [ ]:
"""Funksiyani tekshirish"""
sl_arr_2d = sliced_array_2d() # kesib olingan massiv
assert sl_arr_2d.size == 2  # elementlar soni
assert type(sl_arr_2d) == np.ndarray # #numpy array 

###  Masala(3): Indeks yordamida 3-o'lchamli massivdan elementlarni kesib olish (4 points)

**Masala :**  3-o'lchamli massivni quyidagi listdan yarating, hamda 12, 13, 15, va 16  elementlarini kesib oling. 

                  [[[ 0,  1,  2],
                    [ 3,  4,  5],
                    [ 6,  7,  8]],

                   [[ 9, 10, 11],
                    [12, 13, 14],
                    [15, 16, 17]],

                   [[18, 19, 20],
                    [21, 22, 23],
                    [24, 25, 26]]]

**Yordam :** Avval massivni ikki o'lchamli massivga keltirib, keyin kesib olishni amalga oshiring. 


**Natija:**  

             array([[12, 13],
                    [15, 16]])
ko'rinishida bo'lishi kerak. 

Sizning funksiyangiz massiv elementlari soni, `shape` massiv shakli, hamda elementlari numpy array ekanligi orqali tekshiriladi. Bundan tashqari bir qancha maxfiy testlardan o'tkaziladi (maslahatimiz aldashga urinmang). 

In [ ]:
arr3d = np.arange(27).reshape(3,3,3)

In [ ]:
def sliced_array_3d():
    """Yuqorida yaratilgan massivning elementlari 6 va 7 ga teng bo'lgan qismini kesib olish funksiyasi """
    # YOUR CODE HERE
    return arr3d[1][1:3,:2]
    raise NotImplementedError()

In [ ]:
"""Funksiyani tekshirish"""
sl_arr_3d = sliced_array_3d() # kesib olingan massiv
assert sl_arr_3d.size == 4  # elementlar soni
assert type(sl_arr_3d) == np.ndarray # #numpy array 

###  Masala(4): Boolean indeks yordamida 2-o'lchamli massivlardan elementlarni  kesib olish (2 points)

**Masala :** Bizlarda,  
        
        ['Hasan', 'Husan', 'Javohir', 'Elyor', 'Hasan', 'Javohir', 'Elyor']

**list**dagi kishilar va ularning **ma'lumot**lari 
       
      [[5, 6, 1, 1],
       [9, 1, 1, 1],
       [7, 7, 4, 2],
       [1, 5, 1, 9],
       [9, 9, 4, 5],
       [7, 5, 9, 6],
       [5, 3, 7, 4]]
ko'rinishda keltirilgan. 


Mana shu ma'lumotlardan **Javohir** va **Elyor** ismlariga tegishli ma'lumotlarni Boolean indekslash yordamida kesib olish funksiyasini tuzing. 
**Yordam :** Boolean indekslash video darsligiga murojat qiling. **Natija:** Natija (4, 4) o'lchamli massiv ko'rinishida, hamda dastlabki ikkita qattori quyidagicha

    array([[7, 7, 4, 2],
           [1, 5, 1, 9],
           ...
           ...        ]])

In [ ]:
ismlar = np.array(['Hasan', 'Husan', 'Javohir', 'Elyor', 'Hasan', 'Javohir', 'Elyor'])
malumotlar =   np.array([[5, 6, 1, 1], [9, 1, 1, 1], [7, 7, 4, 2], [1, 5, 1, 9], [9, 9, 4, 5], [7, 5, 9, 6], [5, 3, 7, 4]])

In [ ]:
ismlar == 'Javohir'

array([False, False,  True, False, False,  True, False])

In [ ]:
def boolean_slicing():
    """Boolean indekslash yordamida ma'lumotlarni kesib olish """
    # YOUR CODE HERE
    return malumotlar[(ismlar == 'Javohir') | (ismlar == 'Elyor')]
    raise NotImplementedError()

Sizning funksiyangiz massiv elementlari soni, `shape` massiv shakli, hamda elementlari numpy array ekanligi orqali tekshiriladi. Bundan tashqari bir qancha maxfiy testlardan o'tkaziladi (maslahatimiz aldashga urinmang). 

In [ ]:

"""Funksiyani tekshirish"""
bool_idx = boolean_slicing() # kesib olingan massiv
assert bool_idx.size == 16  # elementlar soni
assert type(bool_idx) == np.ndarray # #numpy array 